### ISSUE TITLE
Icon hard to distinguish with dark menu bar

### ISSUE THREAD

**Issue by kchristidis** [apas/pomodoro#1]
As it says on the tin, the menu bar icon is a bit hard to see when the menu bar is set to dark.

<img width="67" alt="screen shot 2018-04-14 at 13 51 15" src="https://user-images.githubusercontent.com/14876848/38771308-0e1f1694-3fef-11e8-8360-151a66d771df.png">

(A minor issue in the grand scheme of things.)

**Comment by apas** [comment]
Instead of a default black and white icon, what do you think of a colored one?

<img width="414" alt="screenshot 2018-04-15 17 10 55" src="https://user-images.githubusercontent.com/347450/38779969-368673d4-40d0-11e8-8b4b-344737efa43b.png">
<img width="414" alt="screenshot 2018-04-15 17 11 08" src="https://user-images.githubusercontent.com/347450/38779970-38a6c876-40d0-11e8-821a-11c33426115c.png">

**Comment by apas** [comment]
Alternatively, with the original black and white icon:

<img width="412" alt="screenshot 2018-04-15 17 10 03" src="https://user-images.githubusercontent.com/347450/38779971-4658d05e-40d0-11e8-8dcf-38440098eb81.png">
<img width="412" alt="screenshot 2018-04-15 17 10 17" src="https://user-images.githubusercontent.com/347450/38779972-47edb86c-40d0-11e8-9195-0852ad938ca8.png">

**Comment by apas** [comment]
Black and white it is.

**Comment by kchristidis** [comment]
Yeah, I like the black and white one as well. (And, I'm going on memory here, but I think monochromatic icons in the menu bar are either the established norm or what the HIG suggest.)
